### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by azerupi** [azerupi/ecam-kitbox#1]
Tracking issue for the class diagram.

**Comment by azerupi** [comment]
## Current Status:
It's not done, there are a couple of mistakes and it can probably be improved.


![class-diagram](https://cloud.githubusercontent.com/assets/7647338/22655474/89dc3338-ec90-11e6-8e4c-799aeaaf4ce0.png)

**Comment by bluebeel** [comment]
I redrew a diagram using another approach:
![testclassdiagram](https://cloud.githubusercontent.com/assets/13916626/22697822/f32bf432-ed52-11e6-869e-0c452b493511.jpg)

I used the design pattern factory. In Factory pattern, we create object without exposing the creation logic to the client and refer to newly created object using a common interface.
So I created a IProduct interface and concrete classes implementing it, a factory class ProductFactory and a manager class. Our Manager class will use ProductFactory to get a IProduct object. It will pass the necessary information information listed in the different enumerations to ProductFactory to get the type of object it needs then creates it.

What do you think of this approach? @azerupi

**Comment by JonathanPetit** [comment]
I prefer approach by @bluebeel. It's clearer and i think, It is less difficult to implement. Also, it's easier to add a implementation of a new bloc.

But, I think it should have a better way for color enumeration. We could assemble them in one enum or other way? And also, it is necessary to think about the different materials of panel (glass or wood) because they don't have the same property.

**Comment by bluebeel** [comment]
@JonathanPetit I put them in different enumerations because in the .csv file each color is not used for each product.
<img width="324" alt="capture d ecran 2017-02-07 a 17 10 11" src="https://cloud.githubusercontent.com/assets/13916626/22699631/4fe223d6-ed58-11e6-9b32-19c9891b23de.png">

**Comment by WilliamHdd** [comment]
@azerupi  's diagram is easier to understand to me but both look great. No constructive comments to give :)

**Comment by bluebeel** [comment]
Order class diagram. What do you think about?
![classdiagramorder](https://cloud.githubusercontent.com/assets/13916626/22862133/0edbba26-f129-11e6-9e24-3d0a8999961a.jpg)

**Comment by azerupi** [comment]
What is `OrderLine` supposed to be? 
Other than that, `Orders` should be `Order` without **s**. And `Product` will be the same base class from the other class diagram right?

Looks mostly good to me :)

**Comment by bluebeel** [comment]
Yes, Product is the same base class.
OrderLine represents a line in the order so a particular product. This diagram represents more how a order should be represented in the bd.
The Order table contains just its PK and a FK for the client.
The OrderLine table contains all rows of all commands. What allows us to differentiate between 2 orders is the FK OrderId. It also has a FK for the products which allows us to have only one existence of the product in the db but the same reference in several orders.
The ER diagram :
![erddiagramorder](https://cloud.githubusercontent.com/assets/13916626/22862443/eafcf63c-f12e-11e6-85fc-1eb86ae82e81.jpg)

**Comment by azerupi** [comment]
I see, in that case I would personally rename it to `OrderItem`. 

Also, there is no need to copy all the properties inside it. I think only the `Product` and the `quantity` need to be stored in it. `OderId` is redundant because `OrderItem` is stored in an `Order` who knows his own id. The same thing applies to `ProductId` and `UnitCost`. `SubTotal` can be computed from the quantity and the price, so no need to store it.

Of course this is different for that database tables.

**Comment by azerupi** [comment]
![class-diagram](https://cloud.githubusercontent.com/assets/7647338/22877671/cede5ed4-f1d6-11e6-8025-e05fd0df0a7f.png)

**Comment by bluebeel** [comment]
Should we make a class diagram for the Order, User and database management?

**Comment by azerupi** [comment]
Maybe, I am not sure how exhaustive the diagrams should be. The representation of the orders are more useful for the database which we have. I am not sure if it adds a lot of value to make a diagram for the in-program representation.

**Comment by azerupi** [comment]
I am going to close this, create a new issue if you think we should make a second class diagram for the ordering part. :)
