### ISSUE TITLE
DB & ORM

### ISSUE THREAD

**Issue by azerupi** [azerupi/ecam-kitbox#2]
This is an issue to discuss what database to use and which ORM to use (if any).

### Database
We can choose between:

- MySQL
- PostgreSQL
- SQLite (however I'm not sure they will like that...)

Of course, if we choose to use an ORM, the database should be supported by that ORM.

### ORM
If we choose to use an ORM, it has to be simple to use and setup. It should also have decent documentation.

Let's discuss and come to an agreement.

**Comment by bluebeel** [comment]
I did a little research to see what's there for ç #.
There are three that stand out:

- **Entity framework:** it is the official orm and maintained by microsoft, it is well documented and complete (perhaps too much for our project?)
_Useful links:_
Http://www.entityframeworktutorial.net/EntityFramework5/entity-framework5-introduction.aspx
Https://msdn.microsoft.com/en-us/library/bb399567(v=vs.110).aspx

- **PetaPoco:** it is an open-source orm and always updated. For what I have seen, it seems to be the simplest to take in hand and it is rather well documented
_Useful link:_ https://github.com/CollaboratingPlatypus/PetaPoco

- **Massive:** another orm like PetaPoco
_Useful link:_ https://github.com/FransBouma/Massive

At first sight, my choice would turn to PetaPoco or Massive. After that you have to take a closer look at the documentation.

For the database I think we can stay on MySQL. I do not think it is necessary to switch to PostgresSQL given the size of the database.

**Comment by JonathanPetit** [comment]
I agree with @bluebeel to stay in MySQL if it's possible with ORM. Because it's simple to use MySQL and like @bluebeel say it's not necessary with own size of the database.

But i don't know much about ORM. I let you work on it or you want me to start research?

**Comment by bluebeel** [comment]
A small link that explains what an orm is:
[https://www.fullstackpython.com/object-relational-mappers-orms.html](url)

**Comment by WilliamHdd** [comment]
I agree, we all have notions of MySQL and it works fine, why change ? I'm not completely sure to understand what an ORM does, but it looks pretty useful so let's use it if it's not to hard to master .

**Comment by bluebeel** [comment]
Database: MySQL
ORM: No
