### ISSUE TITLE
Correction of sequence diagram

### ISSUE THREAD

**Issue by JonathanPetit** [azerupi/ecam-kitbox#27]
The sequence diagram contains a dummy title that should be changed or removed.

![capture d ecran 2017-02-20 a 13 50 18](https://cloud.githubusercontent.com/assets/17042782/23125735/84ba688c-f773-11e6-80dc-008bf2a35502.png)

**Comment by JonathanPetit** [comment]
Correction this:
![capture d ecran 2017-02-20 a 13 52 34](https://cloud.githubusercontent.com/assets/17042782/23125804/d97e8c36-f773-11e6-9d7c-65954bc49d84.png)

like this:
![capture d ecran 2017-02-20 a 13 52 41](https://cloud.githubusercontent.com/assets/17042782/23125805/d980c258-f773-11e6-83fa-eac09b114538.png)

**Comment by JonathanPetit** [comment]
Correction the title of message 2, 7, 9, 11.
And the message must be placed on the rigth of the arrow.

**Comment by bluebeel** [comment]
Closed #32
