### ISSUE TITLE
Entity-Relation Diagram

### ISSUE THREAD

**Issue by azerupi** [azerupi/ecam-kitbox#6]
Tracking issue for the entity-relation diagram

**Comment by JonathanPetit** [comment]
It's my first draft of the ER diagram. What do you think? 

![capture d ecran 2017-02-12 a 18 10 19](https://cloud.githubusercontent.com/assets/17042782/22864308/46a208cc-f14f-11e6-8dda-eea0ab61330a.png)

**Comment by JonathanPetit** [comment]
ER diagram version 2.
![erddiagramv2](https://cloud.githubusercontent.com/assets/17042782/22876122/6a8bb2ee-f1cf-11e6-8cad-8c5d0934bb03.png)

**Comment by JonathanPetit** [comment]
Closes view pull request #10
