### ISSUE TITLE
Mock-up

### ISSUE THREAD

**Issue by azerupi** [azerupi/ecam-kitbox#7]
Tracking issue for the mock-up

**Comment by bluebeel** [comment]
**_Currently :_**
![3](https://cloud.githubusercontent.com/assets/13916626/22863923/aec17994-f148-11e6-8f6c-0a6b3cf41b1a.png)
![1](https://cloud.githubusercontent.com/assets/13916626/22863921/ace19992-f148-11e6-8183-e713ef220623.png)
![2](https://cloud.githubusercontent.com/assets/13916626/22863922/adae7f20-f148-11e6-9f53-d58460a701dc.png)

**_TODO :_**

- [ ] Login page
- [ ] Sign up page
- [ ] Resume page
